#!/usr/bin/env python3
"""Generate the AnyStorage enum-dispatch delegation from the trait definitions.

Phase 1 of RFC-046. Reads the two storage traits plus the inherent behaviour
methods on SurrealStorage, and emits the delegating impls for AnyStorage.

Writes rust/rivers-core/src/storage/any.rs and formats it.
Run from the repo root:  python3 scripts/gen_any_storage.py
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

MOD = Path("rust/rivers-core/src/storage/mod.rs")
BACKEND = Path("rust/rivers-core/src/storage/surrealdb_backend.rs")
OUT = Path("rust/rivers-core/src/storage/any.rs")

HEADER = '''//! Backend dispatch across the supported storage engines.
//!
//! GENERATED by `scripts/gen_any_storage.py` — re-run it after changing
//! `StorageBackend`, `PerCodeLocationStorage`, or the inherent methods on
//! `SurrealStorage`.
//!
//! An enum rather than `dyn StorageBackend` because the traits are RPITIT and
//! so are not object-safe, and rather than a type parameter because
//! `#[pyclass] PyStorage` cannot be generic.

use std::future::Future;

use anyhow::Result;

use super::surrealdb_backend::{Capability, SurrealConnectConfig, SurrealStorage};
use super::*;

/// A storage backend, chosen at connect time.
pub enum AnyStorage {
    Surreal(SurrealStorage),
}

impl std::fmt::Debug for AnyStorage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.label())
    }
}

impl From<SurrealStorage> for AnyStorage {
    fn from(inner: SurrealStorage) -> Self {
        Self::Surreal(inner)
    }
}
'''

CONSTRUCTORS = '''    /// Embedded SurrealDB over RocksDB at `path` — the local-dev backend.
    pub async fn surreal_embedded(path: &str) -> Result<Self> {
        Ok(Self::Surreal(SurrealStorage::new_embedded(path).await?))
    }

    pub async fn surreal_embedded_with_capability(path: &str, cap: Capability) -> Result<Self> {
        Ok(Self::Surreal(
            SurrealStorage::new_embedded_with_capability(path, cap).await?,
        ))
    }

    pub fn surreal_embedded_blocking(path: &str) -> Result<Self> {
        Ok(Self::Surreal(SurrealStorage::new_embedded_blocking(path)?))
    }

    /// In-memory SurrealDB — tests only, no durability.
    pub async fn surreal_memory() -> Result<Self> {
        Ok(Self::Surreal(SurrealStorage::new_memory().await?))
    }

    pub fn surreal_memory_blocking() -> Result<Self> {
        Ok(Self::Surreal(SurrealStorage::new_memory_blocking()?))
    }

    /// Remote SurrealDB server.
    pub async fn surreal_connect(config: SurrealConnectConfig) -> Result<Self> {
        Ok(Self::Surreal(SurrealStorage::connect(config).await?))
    }

    pub async fn surreal_connect_with_capability(
        config: SurrealConnectConfig,
        cap: Capability,
    ) -> Result<Self> {
        Ok(Self::Surreal(
            SurrealStorage::connect_with_capability(config, cap).await?,
        ))
    }

    /// Human-readable backend label for logs.
    pub fn label(&self) -> String {
        match self {
            Self::Surreal(inner) => inner.backend_kind().label(),
        }
    }
'''

# Inherent methods that are constructors or config, not behaviour to delegate.
CTOR_RE = re.compile(
    r"^(new_|connect|unauthenticated|with_credentials|label|backend_kind)"
)


def _block_after(src: str, start: int) -> str:
    """Body of a column-0 item starting at `start`, ending at the next `^}$`.

    Counting braces does not work here: the SurrealQL query strings in the
    backend contain `{` and `}`. The tree is rustfmt-formatted, so a top-level
    item always closes with a `}` in column 0.
    """
    end = re.search(r"^\}$", src[start:], re.M)
    if not end:
        sys.exit("unterminated top-level block")
    return src[start : start + end.start()]


def trait_body(src: str, name: str) -> str:
    """Return the body of `trait <name>`."""
    m = re.search(rf"^(?:pub(?:\(crate\))? )?trait {name}\b.*?\{{$", src, re.M)
    if not m:
        sys.exit(f"trait {name} not found")
    return _block_after(src, m.end())


def impl_bodies(src: str, header: str) -> list[str]:
    """Return the body of every `impl ...` block with this exact header.

    `SurrealStorage` has three separate inherent impl blocks, so matching only
    the first would silently drop methods.
    """
    bodies = [
        _block_after(src, m.end())
        for m in re.finditer(rf"^{re.escape(header)} \{{$", src, re.M)
    ]
    if not bodies:
        sys.exit(f"impl block {header!r} not found")
    return bodies


def split_args(arglist: str) -> list[str]:
    """Split a Rust argument list on top-level commas."""
    out, depth, cur = [], 0, ""
    for ch in arglist:
        if ch in "<([":
            depth += 1
        elif ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur)
    return [a.strip() for a in out if a.strip()]


def arg_names(args: list[str]) -> list[str]:
    """Extract the binding name from each `name: Type` argument."""
    names = []
    for a in args:
        if a.startswith("&self") or a == "self":
            continue
        names.append(a.split(":", 1)[0].strip())
    return names


def parse_trait_decls(body: str) -> list[tuple[str, str, str]]:
    """Parse `fn name(args) -> impl Future<Output = R> + Send;` declarations.

    Returns (name, arglist, return_type). Skips provided methods (those with a
    body) and anything that is not an async trait method.
    """
    out = []
    # declaration ends with `;` — provided methods end with `{`
    pat = re.compile(
        r"\n    fn (\w+)\s*\(([^;{]*?)\)\s*->\s*impl Future<Output = (.+?)> \+ Send;",
        re.S,
    )
    for m in pat.finditer("\n" + body):
        name, arglist, ret = m.group(1), m.group(2), m.group(3).strip()
        out.append((name, arglist, ret))
    return out


def parse_inherent(body: str) -> list[tuple[str, str, str]]:
    """Parse inherent `pub async fn name(args) -> Result<R> {` behaviour methods."""
    out = []
    pat = re.compile(r"\n    pub async fn (\w+)\s*\(([^;{]*?)\)\s*->\s*(.+?)\s*\{", re.S)
    for m in pat.finditer("\n" + body):
        name, arglist, ret = m.group(1), m.group(2), m.group(3).strip()
        if CTOR_RE.match(name):
            continue
        if "impl " in ret:
            sys.exit(f"{name} returns an opaque type; delegate it by hand")
        out.append((name, arglist, ret))
    return out


def render_trait_method(name: str, arglist: str, ret: str) -> str:
    args = split_args(arglist)
    names = arg_names(args)
    sig_args = ", ".join(a for a in args)
    call = ", ".join(names)
    return (
        f"    fn {name}({sig_args}) -> impl Future<Output = {ret}> + Send {{\n"
        f"        async move {{\n"
        f"            match self {{\n"
        f"                Self::Surreal(inner) => inner.{name}({call}).await,\n"
        f"            }}\n"
        f"        }}\n"
        f"    }}\n"
    )


def render_inherent_method(name: str, arglist: str, ret: str) -> str:
    args = split_args(arglist)
    names = arg_names(args)
    sig_args = ", ".join(a for a in args)
    call = ", ".join(names)
    return (
        f"    pub async fn {name}({sig_args}) -> {ret} {{\n"
        f"        match self {{\n"
        f"            Self::Surreal(inner) => inner.{name}({call}).await,\n"
        f"        }}\n"
        f"    }}\n"
    )


def main() -> None:
    mod_src = MOD.read_text()
    backend_src = BACKEND.read_text()

    sb = parse_trait_decls(trait_body(mod_src, "StorageBackend"))
    pcl = parse_trait_decls(trait_body(mod_src, "PerCodeLocationStorage"))
    inh = []
    for body in impl_bodies(backend_src, "impl SurrealStorage"):
        inh += parse_inherent(body)
    inh.sort(key=lambda m: m[0])

    print(f"// StorageBackend: {len(sb)} methods", file=sys.stderr)
    print(f"// PerCodeLocationStorage: {len(pcl)} methods", file=sys.stderr)
    print(f"// inherent behaviour: {len(inh)} methods", file=sys.stderr)

    out = [HEADER]
    out.append("impl AnyStorage {")
    out.append(CONSTRUCTORS)
    out += [render_inherent_method(*m) for m in inh]
    out.append("}\n")
    out.append("impl StorageBackend for AnyStorage {")
    out += [render_trait_method(*m) for m in sb]
    out.append("}\n")
    out.append("impl PerCodeLocationStorage for AnyStorage {")
    out += [render_trait_method(*m) for m in pcl]
    out.append("}")

    OUT.write_text("\n".join(out))
    subprocess.run(["rustfmt", "--edition", "2024", str(OUT)], check=True)
    print(f"wrote {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
