[rivers.module]
path = "package_demo.repository"
repo_var = "repo"

[rivers.storage]
path = ".rivers/storage/"

[rivers.server]
host = "127.0.0.1"
port = 3000
grpc_port = 3001

[rivers.daemon]
no_daemon = false
