//! Backend dispatch across the supported storage engines.
//!
//! GENERATED by `scripts/gen_any_storage.py` — re-run it after changing
//! `StorageBackend`, `PerCodeLocationStorage`, or the inherent methods on
//! `SurrealStorage`.
//!
//! An enum rather than `dyn StorageBackend` because the traits are RPITIT and
//! so are not object-safe, and rather than a type parameter because
//! `#[pyclass] PyStorage` cannot be generic.

use std::future::Future;

use anyhow::Result;

use super::surrealdb_backend::{Capability, SurrealConnectConfig, SurrealStorage};
use super::*;

/// A storage backend, chosen at connect time.
pub enum AnyStorage {
    Surreal(SurrealStorage),
}

impl std::fmt::Debug for AnyStorage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.label())
    }
}

impl From<SurrealStorage> for AnyStorage {
    fn from(inner: SurrealStorage) -> Self {
        Self::Surreal(inner)
    }
}

impl AnyStorage {
    /// Embedded SurrealDB over RocksDB at `path` — the local-dev backend.
    pub async fn surreal_embedded(path: &str) -> Result<Self> {
        Ok(Self::Surreal(SurrealStorage::new_embedded(path).await?))
    }

    pub async fn surreal_embedded_with_capability(path: &str, cap: Capability) -> Result<Self> {
        Ok(Self::Surreal(
            SurrealStorage::new_embedded_with_capability(path, cap).await?,
        ))
    }

    pub fn surreal_embedded_blocking(path: &str) -> Result<Self> {
        Ok(Self::Surreal(SurrealStorage::new_embedded_blocking(path)?))
    }

    /// In-memory SurrealDB — tests only, no durability.
    pub async fn surreal_memory() -> Result<Self> {
        Ok(Self::Surreal(SurrealStorage::new_memory().await?))
    }

    pub fn surreal_memory_blocking() -> Result<Self> {
        Ok(Self::Surreal(SurrealStorage::new_memory_blocking()?))
    }

    /// Remote SurrealDB server.
    pub async fn surreal_connect(config: SurrealConnectConfig) -> Result<Self> {
        Ok(Self::Surreal(SurrealStorage::connect(config).await?))
    }

    pub async fn surreal_connect_with_capability(
        config: SurrealConnectConfig,
        cap: Capability,
    ) -> Result<Self> {
        Ok(Self::Surreal(
            SurrealStorage::connect_with_capability(config, cap).await?,
        ))
    }

    /// Human-readable backend label for logs.
    pub fn label(&self) -> String {
        match self {
            Self::Surreal(inner) => inner.backend_kind().label(),
        }
    }

    pub async fn enqueue_backfill_runs(
        &self,
        records: &[RunRecord],
        backfill_id: &str,
    ) -> Result<bool> {
        match self {
            Self::Surreal(inner) => inner.enqueue_backfill_runs(records, backfill_id).await,
        }
    }

    pub async fn enqueue_run(&self, record: &RunRecord) -> Result<()> {
        match self {
            Self::Surreal(inner) => inner.enqueue_run(record).await,
        }
    }

    pub async fn enqueue_runs(&self, records: &[RunRecord]) -> Result<()> {
        match self {
            Self::Surreal(inner) => inner.enqueue_runs(records).await,
        }
    }

    pub async fn fail_backfill(&self, backfill_id: &str, error: &str) -> Result<()> {
        match self {
            Self::Surreal(inner) => inner.fail_backfill(backfill_id, error).await,
        }
    }

    pub async fn get_all_backfills_page(
        &self,
        offset: u64,
        limit: u64,
        filter: &BackfillFilter,
    ) -> Result<BackfillsPage> {
        match self {
            Self::Surreal(inner) => inner.get_all_backfills_page(offset, limit, filter).await,
        }
    }

    pub async fn get_all_backfills_summary(&self) -> Result<BackfillsSummary> {
        match self {
            Self::Surreal(inner) => inner.get_all_backfills_summary().await,
        }
    }

    pub async fn get_all_last_run_per_job(
        &self,
        job_names: &[String],
    ) -> Result<Vec<(String, RunRecord)>> {
        match self {
            Self::Surreal(inner) => inner.get_all_last_run_per_job(job_names).await,
        }
    }

    pub async fn get_all_runs_page(
        &self,
        offset: u64,
        limit: u64,
        filter: &RunFilter,
    ) -> Result<RunsPage> {
        match self {
            Self::Surreal(inner) => inner.get_all_runs_page(offset, limit, filter).await,
        }
    }

    pub async fn get_all_runs_summary(&self, cutoff_24h_ns: i64) -> Result<RunsSummary> {
        match self {
            Self::Surreal(inner) => inner.get_all_runs_summary(cutoff_24h_ns).await,
        }
    }

    pub async fn get_backfills_page(
        &self,
        code_location_id: &str,
        offset: u64,
        limit: u64,
        filter: &BackfillFilter,
    ) -> Result<BackfillsPage> {
        match self {
            Self::Surreal(inner) => {
                inner
                    .get_backfills_page(code_location_id, offset, limit, filter)
                    .await
            }
        }
    }

    pub async fn get_backfills_summary(&self, code_location_id: &str) -> Result<BackfillsSummary> {
        match self {
            Self::Surreal(inner) => inner.get_backfills_summary(code_location_id).await,
        }
    }

    pub async fn get_events_for_asset_page(
        &self,
        code_location_id: &str,
        asset_key: &str,
        event_types: &[String],
        offset: u64,
        limit: u64,
    ) -> Result<(Vec<StoredEvent>, u64)> {
        match self {
            Self::Surreal(inner) => {
                inner
                    .get_events_for_asset_page(
                        code_location_id,
                        asset_key,
                        event_types,
                        offset,
                        limit,
                    )
                    .await
            }
        }
    }

    pub async fn get_last_run_per_job(
        &self,
        code_location_id: &str,
        job_names: &[String],
    ) -> Result<Vec<(String, RunRecord)>> {
        match self {
            Self::Surreal(inner) => {
                inner
                    .get_last_run_per_job(code_location_id, job_names)
                    .await
            }
        }
    }

    pub async fn get_run_asset_events_page(
        &self,
        run_id: &str,
        asset_key: &str,
        event_type: &str,
        offset: u64,
        limit: u64,
    ) -> Result<(Vec<StoredEvent>, u64)> {
        match self {
            Self::Surreal(inner) => {
                inner
                    .get_run_asset_events_page(run_id, asset_key, event_type, offset, limit)
                    .await
            }
        }
    }

    pub async fn get_run_step_events(&self, run_id: &str) -> Result<Vec<StoredEvent>> {
        match self {
            Self::Surreal(inner) => inner.get_run_step_events(run_id).await,
        }
    }

    pub async fn get_run_structured_events_page(
        &self,
        run_id: &str,
        asset_key: Option<&str>,
        offset: u64,
        limit: u64,
    ) -> Result<(Vec<StoredEvent>, u64)> {
        match self {
            Self::Surreal(inner) => {
                inner
                    .get_run_structured_events_page(run_id, asset_key, offset, limit)
                    .await
            }
        }
    }

    pub async fn get_runs_page(
        &self,
        code_location_id: &str,
        offset: u64,
        limit: u64,
        filter: &RunFilter,
    ) -> Result<RunsPage> {
        match self {
            Self::Surreal(inner) => {
                inner
                    .get_runs_page(code_location_id, offset, limit, filter)
                    .await
            }
        }
    }

    pub async fn get_runs_summary(
        &self,
        code_location_id: &str,
        cutoff_24h_ns: i64,
    ) -> Result<RunsSummary> {
        match self {
            Self::Surreal(inner) => {
                inner
                    .get_runs_summary(code_location_id, cutoff_24h_ns)
                    .await
            }
        }
    }

    pub async fn link_backfill_run(&self, backfill_id: &str, run_id: &str) -> Result<bool> {
        match self {
            Self::Surreal(inner) => inner.link_backfill_run(backfill_id, run_id).await,
        }
    }

    pub async fn resume_stalled_backfill(&self, backfill_id: &str) -> Result<bool> {
        match self {
            Self::Surreal(inner) => inner.resume_stalled_backfill(backfill_id).await,
        }
    }

    pub async fn subscribe_table(
        &self,
        table: &str,
    ) -> Result<futures_util::stream::BoxStream<'static, ()>> {
        match self {
            Self::Surreal(inner) => inner.subscribe_table(table).await,
        }
    }
}

impl StorageBackend for AnyStorage {
    fn store_event(&self, event: &EventRecord) -> impl Future<Output = Result<String>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.store_event(event).await,
            }
        }
    }

    fn store_events(
        &self,
        events: &[EventRecord],
    ) -> impl Future<Output = Result<Vec<String>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.store_events(events).await,
            }
        }
    }

    fn get_events_for_run(
        &self,
        run_id: &str,
    ) -> impl Future<Output = Result<Vec<StoredEvent>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_events_for_run(run_id).await,
            }
        }
    }

    fn store_run_logs(&self, logs: &[LogRecord]) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.store_run_logs(logs).await,
            }
        }
    }

    fn get_run_logs(&self, run_id: &str) -> impl Future<Output = Result<Vec<StoredLog>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_run_logs(run_id).await,
            }
        }
    }

    fn step_completion(
        &self,
        asset_key: &str,
        run_ids: &[String],
    ) -> impl Future<Output = Result<(bool, Vec<String>)>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.step_completion(asset_key, run_ids).await,
            }
        }
    }

    fn create_run(&self, run: &RunRecord) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.create_run(run).await,
            }
        }
    }

    fn create_runs(&self, runs: &[RunRecord]) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.create_runs(runs).await,
            }
        }
    }

    fn update_run_status(
        &self,
        run_id: &str,
        status: RunStatus,
        end_time: Option<i64>,
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.update_run_status(run_id, status, end_time).await,
            }
        }
    }

    fn try_start_run(&self, run_id: &str) -> impl Future<Output = Result<bool>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.try_start_run(run_id).await,
            }
        }
    }

    fn update_run_block_reason(
        &self,
        run_id: &str,
        reason: Option<&str>,
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.update_run_block_reason(run_id, reason).await,
            }
        }
    }

    fn get_run(&self, run_id: &str) -> impl Future<Output = Result<Option<RunRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_run(run_id).await,
            }
        }
    }

    fn get_runs_by_ids(
        &self,
        run_ids: &[String],
        status: Option<RunStatus>,
    ) -> impl Future<Output = Result<Vec<RunRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_runs_by_ids(run_ids, status).await,
            }
        }
    }

    fn get_all_runs(
        &self,
        limit: usize,
        status: Option<RunStatus>,
    ) -> impl Future<Output = Result<Vec<RunRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_all_runs(limit, status).await,
            }
        }
    }

    fn get_all_runs_since(
        &self,
        since_timestamp: i64,
        status: Option<RunStatus>,
    ) -> impl Future<Output = Result<Vec<RunRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_all_runs_since(since_timestamp, status).await,
            }
        }
    }

    fn get_all_queued_runs(&self) -> impl Future<Output = Result<Vec<RunRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_all_queued_runs().await,
            }
        }
    }

    fn count_in_progress_runs(&self) -> impl Future<Output = Result<usize>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.count_in_progress_runs().await,
            }
        }
    }

    fn get_in_progress_runs(&self) -> impl Future<Output = Result<Vec<RunRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_in_progress_runs().await,
            }
        }
    }

    fn get_observations_since(
        &self,
        code_location_id: &str,
        since_timestamp: i64,
    ) -> impl Future<Output = Result<Vec<StoredEvent>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_observations_since(code_location_id, since_timestamp)
                        .await
                }
            }
        }
    }

    fn get_latest_observation_ts(
        &self,
        code_location_id: &str,
    ) -> impl Future<Output = Result<Option<i64>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_latest_observation_ts(code_location_id).await,
            }
        }
    }

    fn kv_get(&self, key: &str) -> impl Future<Output = Result<Option<Vec<u8>>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.kv_get(key).await,
            }
        }
    }

    fn kv_set(&self, key: &str, value: &[u8]) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.kv_set(key, value).await,
            }
        }
    }

    fn store_tick(&self, tick: &TickRecord) -> impl Future<Output = Result<String>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.store_tick(tick).await,
            }
        }
    }

    fn store_ticks_batch(
        &self,
        ticks: &[TickRecord],
    ) -> impl Future<Output = Result<Vec<String>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.store_ticks_batch(ticks).await,
            }
        }
    }

    fn store_condition_tick(
        &self,
        tick: &ConditionTickRecord,
    ) -> impl Future<Output = Result<String>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.store_condition_tick(tick).await,
            }
        }
    }

    fn store_condition_evals_batch(
        &self,
        evals: &[ConditionEvalRecord],
    ) -> impl Future<Output = Result<Vec<String>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.store_condition_evals_batch(evals).await,
            }
        }
    }

    fn create_backfill(
        &self,
        backfill: &BackfillRecord,
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.create_backfill(backfill).await,
            }
        }
    }

    fn update_backfill_status(
        &self,
        backfill_id: &str,
        status: BackfillStatus,
        end_time: Option<i64>,
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .update_backfill_status(backfill_id, status, end_time)
                        .await
                }
            }
        }
    }

    fn update_backfill_progress(
        &self,
        backfill_id: &str,
        run_ids: &[String],
        completed: &[PartitionKey],
        failed: &[PartitionKey],
        canceled: &[PartitionKey],
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .update_backfill_progress(backfill_id, run_ids, completed, failed, canceled)
                        .await
                }
            }
        }
    }

    fn get_backfill(
        &self,
        backfill_id: &str,
    ) -> impl Future<Output = Result<Option<BackfillRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_backfill(backfill_id).await,
            }
        }
    }

    fn try_complete_backfill(
        &self,
        backfill_id: &str,
        extra_canceled: &[PartitionKey],
    ) -> impl Future<Output = Result<Option<BackfillStatus>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .try_complete_backfill(backfill_id, extra_canceled)
                        .await
                }
            }
        }
    }

    fn cancel_backfill(
        &self,
        backfill_id: &str,
    ) -> impl Future<Output = Result<BackfillStatus>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.cancel_backfill(backfill_id).await,
            }
        }
    }

    fn free_concurrency_slots(
        &self,
        run_id: &str,
        step_key: &str,
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.free_concurrency_slots(run_id, step_key).await,
            }
        }
    }

    fn free_concurrency_slots_for_run(
        &self,
        run_id: &str,
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.free_concurrency_slots_for_run(run_id).await,
            }
        }
    }

    fn renew_slot_lease(
        &self,
        run_id: &str,
        step_key: &str,
        lease_duration_secs: u32,
    ) -> impl Future<Output = Result<u32>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .renew_slot_lease(run_id, step_key, lease_duration_secs)
                        .await
                }
            }
        }
    }

    fn free_expired_leases(&self) -> impl Future<Output = Result<u32>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.free_expired_leases().await,
            }
        }
    }

    fn cancel_queued_run(&self, run_id: &str) -> impl Future<Output = Result<bool>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.cancel_queued_run(run_id).await,
            }
        }
    }

    fn delete_run(&self, run_id: &str) -> impl Future<Output = Result<bool>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.delete_run(run_id).await,
            }
        }
    }

    fn get_run_progress(&self, run_id: &str) -> impl Future<Output = Result<RunProgress>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_run_progress(run_id).await,
            }
        }
    }

    fn get_run_outcome(
        &self,
        run_id: &str,
    ) -> impl Future<Output = Result<Option<RunOutcome>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_run_outcome(run_id).await,
            }
        }
    }

    fn set_run_outcome(
        &self,
        run_id: &str,
        outcome: &RunOutcome,
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.set_run_outcome(run_id, outcome).await,
            }
        }
    }

    fn request_cancellation(&self, run_id: &str) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.request_cancellation(run_id).await,
            }
        }
    }

    fn is_cancelled(&self, run_id: &str) -> impl Future<Output = Result<bool>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.is_cancelled(run_id).await,
            }
        }
    }

    fn get_events_for_step(
        &self,
        run_id: &str,
        step_key: &str,
    ) -> impl Future<Output = Result<Vec<StoredEvent>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_events_for_step(run_id, step_key).await,
            }
        }
    }

    fn get_step_terminal_events(
        &self,
        run_id: &str,
        step_key: &str,
    ) -> impl Future<Output = Result<Vec<StoredEvent>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_step_terminal_events(run_id, step_key).await,
            }
        }
    }

    fn get_completed_step_keys(
        &self,
        run_id: &str,
    ) -> impl Future<Output = Result<HashSet<String>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_completed_step_keys(run_id).await,
            }
        }
    }

    fn get_step_data_versions(
        &self,
        run_id: &str,
    ) -> impl Future<Output = Result<HashMap<String, String>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_step_data_versions(run_id).await,
            }
        }
    }
}

impl PerCodeLocationStorage for AnyStorage {
    fn get_events_for_asset(
        &self,
        code_location_id: &str,
        asset_key: &str,
        limit: usize,
    ) -> impl Future<Output = Result<Vec<StoredEvent>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_events_for_asset(code_location_id, asset_key, limit)
                        .await
                }
            }
        }
    }

    fn get_latest_materialization(
        &self,
        code_location_id: &str,
        asset_key: &str,
        partition: Option<&str>,
    ) -> impl Future<Output = Result<Option<StoredEvent>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_latest_materialization(code_location_id, asset_key, partition)
                        .await
                }
            }
        }
    }

    fn register_assets(
        &self,
        code_location_id: &str,
        records: &[AssetRecord],
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.register_assets(code_location_id, records).await,
            }
        }
    }

    fn get_asset_record(
        &self,
        code_location_id: &str,
        asset_key: &str,
    ) -> impl Future<Output = Result<Option<AssetRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_asset_record(code_location_id, asset_key).await,
            }
        }
    }

    fn get_asset_records(
        &self,
        code_location_id: &str,
    ) -> impl Future<Output = Result<Vec<AssetRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_asset_records(code_location_id).await,
            }
        }
    }

    fn get_asset_records_by_keys(
        &self,
        code_location_id: &str,
        keys: &[String],
    ) -> impl Future<Output = Result<Vec<AssetRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_asset_records_by_keys(code_location_id, keys)
                        .await
                }
            }
        }
    }

    fn get_assets_by_tag(
        &self,
        code_location_id: &str,
        tag: &str,
    ) -> impl Future<Output = Result<Vec<AssetRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_assets_by_tag(code_location_id, tag).await,
            }
        }
    }

    fn get_assets_by_kind(
        &self,
        code_location_id: &str,
        kind: &str,
    ) -> impl Future<Output = Result<Vec<AssetRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_assets_by_kind(code_location_id, kind).await,
            }
        }
    }

    fn get_assets_by_group(
        &self,
        code_location_id: &str,
        group: &str,
    ) -> impl Future<Output = Result<Vec<AssetRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_assets_by_group(code_location_id, group).await,
            }
        }
    }

    fn set_block_reason_by_status(
        &self,
        code_location_id: &str,
        status: RunStatus,
        reason: Option<&str>,
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .set_block_reason_by_status(code_location_id, status, reason)
                        .await
                }
            }
        }
    }

    fn coordinator_tick_query(
        &self,
        code_location_id: &str,
    ) -> impl Future<Output = Result<(u32, Vec<CoordinatorRunInfo>, Vec<CoordinatorRunInfo>)>> + Send
    {
        async move {
            match self {
                Self::Surreal(inner) => inner.coordinator_tick_query(code_location_id).await,
            }
        }
    }

    fn get_stalled_not_started_runs(
        &self,
        code_location_id: &str,
        cutoff_ns: i64,
    ) -> impl Future<Output = Result<Vec<String>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_stalled_not_started_runs(code_location_id, cutoff_ns)
                        .await
                }
            }
        }
    }

    fn add_dynamic_partitions(
        &self,
        code_location_id: &str,
        partitions_def_name: &str,
        partition_keys: &[String],
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .add_dynamic_partitions(
                            code_location_id,
                            partitions_def_name,
                            partition_keys,
                        )
                        .await
                }
            }
        }
    }

    fn delete_dynamic_partition(
        &self,
        code_location_id: &str,
        partitions_def_name: &str,
        partition_key: &str,
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .delete_dynamic_partition(
                            code_location_id,
                            partitions_def_name,
                            partition_key,
                        )
                        .await
                }
            }
        }
    }

    fn get_dynamic_partitions(
        &self,
        code_location_id: &str,
        partitions_def_name: &str,
    ) -> impl Future<Output = Result<Vec<String>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_dynamic_partitions(code_location_id, partitions_def_name)
                        .await
                }
            }
        }
    }

    fn has_dynamic_partition(
        &self,
        code_location_id: &str,
        partitions_def_name: &str,
        partition_key: &str,
    ) -> impl Future<Output = Result<bool>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .has_dynamic_partition(code_location_id, partitions_def_name, partition_key)
                        .await
                }
            }
        }
    }

    fn get_ticks(
        &self,
        code_location_id: &str,
        automation_name: &str,
        limit: usize,
    ) -> impl Future<Output = Result<Vec<StoredTick>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_ticks(code_location_id, automation_name, limit)
                        .await
                }
            }
        }
    }

    fn prune_ticks(
        &self,
        code_location_id: &str,
        automation_name: &str,
        max_ticks: usize,
    ) -> impl Future<Output = Result<usize>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .prune_ticks(code_location_id, automation_name, max_ticks)
                        .await
                }
            }
        }
    }

    fn get_condition_ticks(
        &self,
        code_location_id: &str,
        limit: usize,
    ) -> impl Future<Output = Result<Vec<StoredConditionTick>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_condition_ticks(code_location_id, limit).await,
            }
        }
    }

    fn prune_condition_ticks(
        &self,
        code_location_id: &str,
        max_ticks: usize,
    ) -> impl Future<Output = Result<usize>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .prune_condition_ticks(code_location_id, max_ticks)
                        .await
                }
            }
        }
    }

    fn get_condition_evals(
        &self,
        code_location_id: &str,
        asset_key: &str,
        limit: usize,
    ) -> impl Future<Output = Result<Vec<StoredConditionEval>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_condition_evals(code_location_id, asset_key, limit)
                        .await
                }
            }
        }
    }

    fn get_condition_evals_for_tick(
        &self,
        code_location_id: &str,
        tick_id: &str,
    ) -> impl Future<Output = Result<Vec<StoredConditionEval>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_condition_evals_for_tick(code_location_id, tick_id)
                        .await
                }
            }
        }
    }

    fn prune_condition_evals(
        &self,
        code_location_id: &str,
        asset_key: &str,
        max_evals: usize,
    ) -> impl Future<Output = Result<usize>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .prune_condition_evals(code_location_id, asset_key, max_evals)
                        .await
                }
            }
        }
    }

    fn get_partition_events(
        &self,
        code_location_id: &str,
        asset_key: &str,
        partition_key: &str,
        limit: usize,
    ) -> impl Future<Output = Result<Vec<StoredEvent>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_partition_events(code_location_id, asset_key, partition_key, limit)
                        .await
                }
            }
        }
    }

    fn get_materialized_partitions(
        &self,
        code_location_id: &str,
        asset_key: &str,
    ) -> impl Future<Output = Result<Vec<PartitionKey>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_materialized_partitions(code_location_id, asset_key)
                        .await
                }
            }
        }
    }

    fn count_materialized_partitions(
        &self,
        code_location_id: &str,
        asset_key: &str,
    ) -> impl Future<Output = Result<u64>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .count_materialized_partitions(code_location_id, asset_key)
                        .await
                }
            }
        }
    }

    fn count_dynamic_partitions(
        &self,
        code_location_id: &str,
        partitions_def_name: &str,
    ) -> impl Future<Output = Result<u64>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .count_dynamic_partitions(code_location_id, partitions_def_name)
                        .await
                }
            }
        }
    }

    fn get_partition_timestamps(
        &self,
        code_location_id: &str,
        asset_key: &str,
    ) -> impl Future<Output = Result<Vec<(PartitionKey, i64)>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_partition_timestamps(code_location_id, asset_key)
                        .await
                }
            }
        }
    }

    fn get_partition_timestamps_since(
        &self,
        code_location_id: &str,
        asset_key: &str,
        since_timestamp: i64,
    ) -> impl Future<Output = Result<Vec<(PartitionKey, i64)>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_partition_timestamps_since(
                            code_location_id,
                            asset_key,
                            since_timestamp,
                        )
                        .await
                }
            }
        }
    }

    fn get_in_progress_partitions(
        &self,
        code_location_id: &str,
        asset_key: &str,
    ) -> impl Future<Output = Result<Vec<PartitionKey>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_in_progress_partitions(code_location_id, asset_key)
                        .await
                }
            }
        }
    }

    fn get_failed_partitions(
        &self,
        code_location_id: &str,
        asset_key: &str,
        materialized: &HashMap<PartitionKey, i64>,
    ) -> impl Future<Output = Result<HashMap<PartitionKey, i64>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_failed_partitions(code_location_id, asset_key, materialized)
                        .await
                }
            }
        }
    }

    fn get_backfills(
        &self,
        code_location_id: &str,
        limit: Option<usize>,
        status: Option<BackfillStatus>,
    ) -> impl Future<Output = Result<Vec<BackfillRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_backfills(code_location_id, limit, status).await,
            }
        }
    }

    fn set_pool_limit(
        &self,
        code_location_id: &str,
        pool_key: &str,
        limit: i32,
        lease_duration_secs: u32,
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .set_pool_limit(code_location_id, pool_key, limit, lease_duration_secs)
                        .await
                }
            }
        }
    }

    fn get_pool_limits(
        &self,
        code_location_id: &str,
    ) -> impl Future<Output = Result<Vec<PoolLimit>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_pool_limits(code_location_id).await,
            }
        }
    }

    fn get_pool_info(
        &self,
        code_location_id: &str,
        pool_key: &str,
    ) -> impl Future<Output = Result<PoolInfo>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_pool_info(code_location_id, pool_key).await,
            }
        }
    }

    fn get_all_pool_infos(
        &self,
        code_location_id: &str,
    ) -> impl Future<Output = Result<Vec<PoolInfo>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_all_pool_infos(code_location_id).await,
            }
        }
    }

    fn claim_concurrency_slots(
        &self,
        code_location_id: &str,
        pools: &[(String, u32)],
        run_id: &str,
        step_key: &str,
        priority: i32,
        lease_duration_secs: u32,
    ) -> impl Future<Output = Result<ConcurrencyClaimStatus>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .claim_concurrency_slots(
                            code_location_id,
                            pools,
                            run_id,
                            step_key,
                            priority,
                            lease_duration_secs,
                        )
                        .await
                }
            }
        }
    }

    fn get_pool_slot_holders(
        &self,
        code_location_id: &str,
        pool_key: &str,
    ) -> impl Future<Output = Result<Vec<SlotHolder>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_pool_slot_holders(code_location_id, pool_key)
                        .await
                }
            }
        }
    }

    fn get_runs(
        &self,
        code_location_id: &str,
        limit: usize,
        status: Option<RunStatus>,
    ) -> impl Future<Output = Result<Vec<RunRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_runs(code_location_id, limit, status).await,
            }
        }
    }

    fn get_queued_runs(
        &self,
        code_location_id: &str,
    ) -> impl Future<Output = Result<Vec<RunRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_queued_runs(code_location_id).await,
            }
        }
    }

    fn get_runs_since(
        &self,
        code_location_id: &str,
        since_timestamp: i64,
        status: Option<RunStatus>,
        order: SortOrder,
    ) -> impl Future<Output = Result<Vec<RunRecord>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .get_runs_since(code_location_id, since_timestamp, status, order)
                        .await
                }
            }
        }
    }

    fn get_condition_eval_state(
        &self,
        code_location_id: &str,
    ) -> impl Future<Output = Result<Option<crate::condition::ConditionEvalState>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_condition_eval_state(code_location_id).await,
            }
        }
    }

    fn set_condition_eval_state(
        &self,
        code_location_id: &str,
        state: &crate::condition::ConditionEvalState,
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .set_condition_eval_state(code_location_id, state)
                        .await
                }
            }
        }
    }

    fn get_condition_pending_dispatch(
        &self,
        code_location_id: &str,
    ) -> impl Future<Output = Result<Option<crate::condition::PendingDispatch>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner.get_condition_pending_dispatch(code_location_id).await
                }
            }
        }
    }

    fn set_condition_pending_dispatch(
        &self,
        code_location_id: &str,
        pending: &crate::condition::PendingDispatch,
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => {
                    inner
                        .set_condition_pending_dispatch(code_location_id, pending)
                        .await
                }
            }
        }
    }

    fn get_graph_topology(
        &self,
        code_location_id: &str,
    ) -> impl Future<Output = Result<Option<crate::assets::graph::GraphTopology>>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.get_graph_topology(code_location_id).await,
            }
        }
    }

    fn set_graph_topology(
        &self,
        code_location_id: &str,
        topology: &crate::assets::graph::GraphTopology,
    ) -> impl Future<Output = Result<()>> + Send {
        async move {
            match self {
                Self::Surreal(inner) => inner.set_graph_topology(code_location_id, topology).await,
            }
        }
    }
}
